### ISSUE TITLE
Compilation error with smild 4.3.6

### ISSUE THREAD

**Issue by andreaTierra** [tierratelematics/ninjagoat-projections#2]
Hi,
I uploaded my version of ninjagoat from 1.0.0 to 2.3.3 and the relative dependencies ninjagoat-dialogs and ninjagoat-projections.
But when I try to compile my project, smild sayd this 
"node_modules/ninjagoat-projections/declarations/ninjagoat-projections.d.ts(49,32): Error TS2304: Cannot find name 'object'.
node_modules/ninjagoat-projections/declarations/ninjagoat-projections.d.ts(49,41): Error TS2304: Cannot find name 'object'."

The errors are not in my files and I don't understand like resolve them. Can you help me? My email is agambini@topcon.com

**Comment by mtfranchetto** [comment]
Hi, you need to update smild to version 4.4.0 since typescript 2.3 is required.

**Comment by andreaTierra** [comment]
Thanks
